### ISSUE TITLE
the navigation stack from profile to bucket list is odd

### ISSUE THREAD

**Issue by subramanian42** [Spyy004/LifeList#21]
The navigation from profile page to home page should not be pushNamedAndRemoveUntil as the back button lead to user leaving the app which is not a desired behavior. 

<video src="https://user-images.githubusercontent.com/88108372/233085175-5b81f8a0-4b68-47d8-bea5-c88e8fa43f7e.mp4" controls="controls" style="max-height: 200">
</video>

**Comment by Spyy004** [comment]
The idea is to implement dashboard and profile pages as 'Tabs'. So in the context of tabs, few apps allows the user to exit the app from the initial page of the tab whereas some apps treat them as regular navigations which means that if i press back from profile tab I will be taken back to dashboard tab screen or wherever i came from. 
You can go ahead and fix this by changing the functionality from reset to pop but make sure that the app works fine. When you clear data in settings and go back twice, you go back to an old state of dashboard rather than a new state. So you might see the buckets even after you deleted it. If you find a way to fix it then it would be awesome and a noteworthy PR.
